name: Build Alpine Pi Image

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing qemu-user-static binfmt-support

      - name: Enable ARM emulation
        run: |
          sudo update-binfmts --enable qemu-arm

      - name: Download Alpine Pi image
        run: |
          wget https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/armv7/alpine-rpi-3.23.3-armv7.tar.gz

      - name: Extract and modify
        run: |
          mkdir rootfs
          tar -xzf alpine-rpi-3.23.3-armv7.tar.gz -C rootfs
          ls rootfs
          ls rootfs/usr || echo "no usr"
          ls rootfs/bin || echo "no bin"
          
          # Copy qemu into the chroot so ARM binaries can run
          sudo cp /usr/bin/qemu-arm-static rootfs/usr/bin/
          
          # Now chroot works
          sudo chroot rootfs /usr/bin/qemu-arm-static /bin/sh -c "apk update && apk add openssl vim"
          
          tar -czf alpine-rpi-custom.tar.gz -C rootfs .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: alpine-rpi-custom
          path: alpine-rpi-custom.tar.gz
